//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentTable()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int AppointmentID { get; set; }
        public int PaitentID { get; set; }
        public int PhysicianID { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public string Criticality { get; set; }
        public string DoctorNotes { get; set; }
        public string ScheduleStatus { get; set; }
    
        public virtual PaitentTable PaitentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
