//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRequest
    {
        public int DrugRequestID { get; set; }
        public string DrugInfo { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int PhysicianID { get; set; }
        public string Status { get; set; }
        public int ChemistID { get; set; }
    
        public virtual ChemistTable ChemistTable { get; set; }
        public virtual PhysicianTable PhysicianTable { get; set; }
    }
}
