//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicoEntities1 : DbContext
    {
        public ClinicoEntities1()
            : base("name=ClinicoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdviceTable> AdviceTables { get; set; }
        public virtual DbSet<AppointmentTable> AppointmentTables { get; set; }
        public virtual DbSet<ChemistTable> ChemistTables { get; set; }
        public virtual DbSet<DrugRequest> DrugRequests { get; set; }
        public virtual DbSet<DrugTable> DrugTables { get; set; }
        public virtual DbSet<PaitentTable> PaitentTables { get; set; }
        public virtual DbSet<PhysicianTable> PhysicianTables { get; set; }
        public virtual DbSet<PODrugLine> PODrugLines { get; set; }
        public virtual DbSet<POHeader> POHeaders { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SupplierTable> SupplierTables { get; set; }
        public virtual DbSet<Usertable> Usertables { get; set; }
    }
}
